app/views.py
from flask import Blueprint, session, escape, redirect, url_for # se utiliza para importar clases

from . import models
from flask import render_template, request, jsonify #se utiliza para import funsiones.
from werkzeug.security import generate_password_hash, check_password_hash
from .forms import RegisterForm
from datetime import datetime
#",ProductoForm"
from .models import User, Consumo, Article, Carga, Stock, updateStock, StockDeUnaFechaDada, consumoArtRangoDeFecha, cargaArtRangoDeFecha, consultaPorMes, Diferencia



page = Blueprint('page', __name__) #Se almacenan las rustas en esta instancia

@page.route('/', methods=['GET', 'POST'])
def Consumos():
	if request.method == "POST":
		if request.form:
			articulos = ['filtro',
		            'ws2',
		            'colectores',
		            'ependrorf05',
		            'ependrorf02',
		            'ependrorf2',
					'amplificacion',
		            'puntas10',
		            'puntas1000',
		            'ws1',
		            'ssb',
		            'eb',
		            'hisopos',
		            'amplificacion24']

		for articulo in articulos:
			aux = Article.query.filter_by(name=articulo).first()
			if (request.form[articulo] != ""):
				if (float(request.form[articulo]) > 0):
					Consumo.create_element(person = request.form['nombre'],
									   turn = request.form['turno'],
									   article_id = aux,
									   amount = float(request.form[articulo]),
									   date = request.form['fecha'])
					stock = Stock.query.filter_by(article_id=aux.id).first()
					updateStock(object=stock, amount=(-1*float(request.form[articulo]))) #pasa un numero negativo ya que decrementa el inventario

		return redirect("/")

	return render_template('index.html', title='Bienvenido')

@page.app_errorhandler(404)
def page_not_found(error):
	# por convencion los errores se manejas de la siguiente forma,
	# una descripcion del error y el numero del error
	return render_template('errors/404.html', name='Leonardo'), 404


#Los metodos por los cuales podra ser consultada esta url
@page.route('/index', methods=['GET', 'POST']) #SE LE INDICA con que methodos trabajara esta url
def login():
	#form = LoginForm(request.form) #esto permite que cuando se envie informacion del formulario, se capture en la instancia.

	#if request.method == 'POST' and form.validate():
	if request.method == 'POST':
		#el atributo data es el metodos atraver del cual se obtiene el valor que usuario esta enviando al servidor
		user = models.User.query.filter_by(username=request.form['username']).first()

		#cuidar el orden con el que se declaran los argumentos de check_password_hash
		if user and check_password_hash(user.password, request.form['pws']):
			session['username'] = user.username  # asi se crea la cookie de session
			print('Nueva sesion creada!')
			return redirect('/home')
		return "Datos invalidos"



@page.route('/register/', methods=['GET', 'POST'])
def register():
	form = RegisterForm(request.form)

	if request.method == 'POST':
		if form.validate():

			hash_pw = generate_password_hash(form.password.data, method="sha256")
			User.crear_element(form.username.data, hash_pw)
			#redirect, redirecciona a una url
			return redirect("/")

	return render_template('auth/register.html', title="Register", form=form)

@page.route('/home')
def home():
	if 'username' in session: # asi se valida que existe la sesion
		#return "You're %s" % escape(session['username'])
		return render_template('sesion.html', title='Login')
	return "debes loguearte"


@page.route('/logout')
def logout():
	session.pop('username', None)
	#return 'Su sesion fue cerrada satisfactoriamente.'
	return redirect("/")

@page.route('/url_for/uso')
def uso():
	return redirect(url_for('page.home')) #url_for recibe un nombre de una funcion y retorna su ruta.
			#cuando se esta usando programacion modular y se desea usar el metodo url_for, debe colocarse
			# como se muestra en el ejemplo
			#de no sere modular con blueprint se usa sin page.*

@page.route('/cargar', methods=["GET", "POST"])
def cargar():
	if 'username' in session:
		if request.method == "POST":
			articulos = ['filtro',
						 'ws2',
						 'colectores',
						 'ependrorf05',
						 'ependrorf02',
						 'ependrorf2',
						 'puntas10',
						 'puntas1000',
						 'amplificacion',
						 'ws1',
						 'ssb',
						 'eb',
						 'hisopos',
						 'amplificacion24']
			for articulo in articulos:
				aux = Article.query.filter_by(name=articulo).first()
				if (request.form[articulo] != ""):
					if (float(request.form[articulo]) > 0):
						Carga.element(person = request.form['nombre'],
										   turn = request.form['turno'],
										   article_id = aux,
										   amount = float(request.form[articulo]),
										   date = request.form['fecha'])

						stock = Stock.query.filter_by(article_id=aux.id).first()
						updateStock(object=stock, amount=float(request.form[articulo])) #pasa un numero negativo ya que decrementa el inventario



		return render_template("sesion.html", title="Home")
	return "debes loguearte"


from datetime import datetime
@page.route('/consultaConsumo', methods=["GET", "POST"])
def consulta_consumo():
	if 'username' in session:
		if request.method == "POST":
			init = datetime.strptime(str(request.form['inicio']), "%Y-%m-%d")  # casting de str a datetime
			end = datetime.strptime(str(request.form['fin']), "%Y-%m-%d")  # casting de str a datetime
			article = Article.query.all()
			contenedor = []
			if (init <= end):
				for q in article:
					_c =[q.name]
					_c.append(float(format(StockDeUnaFechaDada(q.id, init), '.2f'))) #se formatea el float para que tenga una presicion de 1
					_c.append(float(format(consumoArtRangoDeFecha(q.id, str(init), str(end)),'.2f')))
					_c.append(float(format((_c[1] + (cargaArtRangoDeFecha(q.id, str(init), str(end)) -_c[2])), '.2f')))

					contenedor.append(_c)

			return render_template('tabla_consulta.html', titlce="consulta", consulta = contenedor)
		return render_template('consumo.html', title="consulta")
	return "debes loguearte"

@page.route('/inv', methods=['GET', 'POST'])
def inv():
	stock = Stock.query.all()
	consulta = []
	for row in stock:
		arti = []
		arti.append(row.id)
		aName = Article.query.filter_by(id=row.article_id).first()
		aName = aName.name
		arti.append(aName)
		arti.append(row.amount)
		arti.append(row.created_at)
		consulta.append(arti)

	return render_template('inventario.html', title="Inventario", consulta=consulta)


@page.route('/casalab')
def casaLab():
	StockDeUnaFechaDada(9, datetime.strptime('2022-01-31', "%Y-%m-%d"))
	consumoArtRangoDeFecha(9, '2022-01-1', '2022-01-31')

	return render_template('vistaHomeCorporativa.html', title="Inventario")

@page.route('/consumo', methods=['GET', 'POST'])
def consumoDetallado():
	if 'username' in session:
		if request.method=='POST':
			date = []
			date.append(str(datetime.strptime(str(request.form['inicio']), "%Y-%m-%d")))
			date.append(str(datetime.strptime(str(request.form['fin']), "%Y-%m-%d")))
			#models.db.Query(Article).join(Consumo).filter()
			articulos = request.form.getlist('articulo')
			diccionario = models.consultaDetallada(articulos, date)
			return render_template('dataTable.html', diccionario=diccionario, date=date)

		return render_template('formConsulta.html')

@page.route('/t', methods=['GET', 'POST'])
def consumoMensual():
	if 'username' in session:
		f = 28
		mes = {
			"enero": [1, 31],
			"febrero": [2, f],
			"marzo": [3, 31],
			"abril": [4, 30],
			"mayo": [5, 31],
			"junio": [6, 30],
			"julio": [7, 31],
			"agosto": [8, 31],
			"septiembre": [9, 30],
			"octubre": [10, 31],
			"noviembre": [11, 30],
			"diciembre": [12, 31]
		}
		if request.method=="POST":
			ano = int(request.form['ano'])

			if (ano%4 == 0) and not (ano%100 == 0) and (ano%400 == 0):
				f = 29

			fecha = [f"{ano}-{mes[request.form.getlist('mes')[0]][0]}-01",
					 f"{ano}-{mes[request.form.getlist('mes')[0]][0]}-{mes[request.form.getlist('mes')[0]][1]}"]

			d = consultaPorMes(fecha)
			return render_template("dataTable_consumoMes.html", dicc=d, key=d["consumo"].keys(), ano=ano, mes=request.form["mes"])

		if request.method=="GET":
			return render_template("consumoMensual.html", mes=mes.keys())

@page.route('/diferencias', methods=['GET', 'POST'])
def diferencias():

	if request.method == "POST":
		articulos = ['filtro',
					 'ws2',
					 'colectores',
					 'ependrorf05',
					 'ependrorf02',
					 'ependrorf2',
					 'puntas10',
					 'puntas1000',
					 'amplificacion',
					 'ws1',
					 'ssb',
					 'eb',
					 'hisopos',
					 'amplificacion24']
		for articulo in articulos:
			aux = Article.query.filter_by(name=articulo).first()
			if (request.form[articulo] != ""):
				if (float(request.form[articulo]) < 0 or float(request.form[articulo]) > 0  ):
					Diferencia.create_element(person = request.form['nombre'],
											  turn = request.form['turno'],
											  article_id = aux,
											  amount = float(request.form[articulo]),
											  date = request.form['fecha'])

	return render_template("cargar.html")



"""
def merma():
	if 'username'in session:
		if request.method=='POST':
			if ( request.form['inicio'] != '' and resquest.form['fin'] != '' ): 
				rangoFecha = [request.form['inicio']]
				ranfoFecha.append[request.form['fin']]
				
				if (request.form['articulo') and request.form['person']	):
					 session.Querty
				
			
		


"""

app/templates/consumoMensual.html
{% extends "formConsulta.html" %}

{% block form %}

<form method="POST" class="form-card" action="{{url_for('page.consumoMensual')}}" name="consulta">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"\>
    <div class="form-control col-4 flex-column d-flex">
    <select class="form-control col-4 flex-column d-flex required" name="mes" id="consultaConsumoMensual">
        {% for i in mes %}
        <option name="mes" value="{{i}}">{{i}}</option>
        {% endfor %}
    </select>

    <label class="form-control-label px-3">Año<span class="text-danger"> *</span></label> <input type="number"  name="ano" min="2020" placeholder="Indique el ano" value="2022">
    <div class="row justify-content-end">
    <div class="form-group col-12 flex-column d-flex"> <button type="submit" class="btn-block btn-primary" name="consulta_consumo">Consultar</button> </div>
        </div>
</form>
{% endblock %}

app/templates/index.html
{% extends 'layout.html'%}
{% from 'helpers/_forms.html' import render_field %}

{% block navbar %}
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">

    <div class="container">

        <div class="flex justify-center pt-8 sm:justify-start sm:pt-0">
          <a class="navbar-brand" href="https://pasedesalud.casalab.com.ve">
          <img width="100px" src="{{ url_for('static', filename='img/lab.png')}}" alt="PaseDeSalud">
          </a>
        </div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Activar navegación">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto"></ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto ">
                <!-- Authentication Links -->
                <form action="{{url_for('page.login')}}" method="POST" name="login">
                    <input  type="hidden" name="csrf_token" value="{{ csrf_token() }}"\>

                    <label for="Usuario">
                    <input type="text" placeholder="usuario" class="form-control required " name="username" required>
                	</label>
                    <label for="Clave">
                    <input type="password" placeholder="Clave" class="form-control col-md-10 required" name="pws" required>
                    </label>
                    <label for="boton">
                    <button class="btn btn-primary" type="submit" name="Blogin" >Iniciar Sesión</button>
                    </label>
                </form>
            </ul>
			</div>
		</div>
	</nav>
{% endblock %}

{% block container %}
<style>
    body{color: #000;overflow-x: hidden;height: 100%;background-repeat: no-repeat;background-size: 100% 100%}.card{padding: 30px 40px;margin-top: 60px;margin-bottom: 60px;border: none !important;box-shadow: 0 6px 12px 0 rgba(0,0,0,0.2)}.blue-text{color: #00BCD4}.form-control-label{margin-bottom: 0}input, textarea, button{padding: 8px 15px;border-radius: 5px !important;margin: 5px 0px;box-sizing: border-box;border: 1px solid #ccc;font-size: 18px !important;font-weight: 300}input:focus, textarea:focus{-moz-box-shadow: none !important;-webkit-box-shadow: none !important;box-shadow: none !important;border: 1px solid #00BCD4;outline-width: 0;font-weight: 400}.btn-block{text-transform: uppercase;font-size: 15px !important;font-weight: 400;height: 43px;cursor: pointer}.btn-block:hover{color: #fff !important}button:focus{-moz-box-shadow: none !important;-webkit-box-shadow: none !important;box-shadow: none !important;outline-width: 0}
</style>

<div class="container-fluid px-1 py-5 mx-auto">
    <div class="row d-flex justify-content-center">
        <div class="col-xl-7 col-lg-8 col-md-9 col-11 text-center">
            <h3>Insumos</h3>
            <p class="blue-text">Declare el material utilizado en el laborio<br></p>
            <div class="card ">

                <form method="POST" class="form-card" action="{{url_for('page.Consumos')}}" name="consumo">

                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"\>

                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-1">Fecha<span class="text-danger"> *</span></label> <input type="date"  name="fecha"  placeholder="Indique la fecha" class="required" required> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-1">Turno<span class="text-danger"> *</span></label> <input type="text"  name="turno" placeholder="Indique el turno" class="required" required> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-12 flex-column d-flex"> <label class="form-control-label px-1">Apellido y Nombre<span class="text-danger"> *</span></label> <input type="text"  name="nombre" maxlength="25" placeholder="Indique su nombre" class="required" required> </div>

                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-1">Filtro<span class="text-danger"> </span></label> <input type="number" name="filtro" min="0" placeholder="Numero de piezas" > </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-1">Micro Colectores<span class="text-danger"> </span></label> <input type="number"  min="0" name="colectores" placeholder="Numero de piezas"> </div>

                    </div>
                    <div class="row justify-content-between text-left">

                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-1">Ependorf 0.5<span class="text-danger"> </span></label> <input type="number" name="ependrorf05" min="0" placeholder="Numero de piezas"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-1">Ependorf 0.2<span class="text-danger"> </span></label> <input type="number"  name="ependrorf02" min="0" placeholder="Numero de piezas"> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-1">Ependorf 2<span class="text-danger"> </span></label> <input type="number" name="ependrorf2" min="0" placeholder="Numero de piezas"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-1">Puntas 10<span class="text-danger"> </span></label> <input type="number" name="puntas10" min="0" placeholder="Numero de piezas"> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-1">Puntas 1000<span class="text-danger"> </span></label> <input type="number"  name="puntas1000" min="0" placeholder="Numero de piezas"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Kit Amplificacion 96 <span class="text-danger"> </span></label> <input type="number"  step="0.1" min="0" name="amplificacion" placeholder="Numero de piezas"> </div>

                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-1">WS1 mL<span class="text-danger"> </span></label> <input type="number" step="0.1" name="ws1" min="0" placeholder="Numero de mL"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-1">WS2 mL<span class="text-danger"> </span></label> <input type="number" step="0.1" name="ws2"  min="0"placeholder="Numero de mL"> </div>

                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-1">SSB mL<span class="text-danger"> </span></label> <input type="number" step="0.1" name="ssb"  min="0" placeholder="Numero de mL"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-1">EB mL<span class="text-danger"> </span></label> <input type="number" step="0.1" name="eb"  min="0" placeholder="Numero de mL"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-1">Hisopo<span class="text-danger"></span></label> <input type="number"  name="hisopos" min="0" placeholder="Numero de piezas"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Kit Amplificacion 24 <span class="text-danger"> </span></label> <input type="number"  step="0.1" min="0" name="amplificacion24" placeholder="Numero de piezas"> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-12 flex-column d-flex"> <label class="form-control-label px-1">Observaciones<span class="text-danger"> </span></label> <input type="text" name="observacion" placeholder="Observaciones"> </div>
                    </div>
                    <div class="row justify-content-end">
                        <div class="form-group col-sm-6"> <button type="submit" class="btn-block btn-primary" name="Bconsumo">Consumo de Insumos</button> </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/sesion.html
{% extends 'layout.html'%}
{% from 'helpers/_forms.html' import render_field %}

{% block navbar %}
{% block scripts %}
<script src="{{url_for('static', filename='js/bootstrap.min.js' )}}" ></script>
<script src="{{ url_for('static', filename='js/jquery-3.5.1.js')}}"></script>
<script src="{{ url_for('static', filename='js/popper.min.js')}}"></script>
{% endblock %}
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">

    <div class="container">

        <div class="flex justify-center pt-8 sm:justify-start sm:pt-0">
          <a class="navbar-brand" href="https://pasedesalud.casalab.com.ve">
          <img width="100px" src="{{ url_for('static', filename='img/lab.png')}}" alt="PaseDeSalud">
          </a>
        </div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Activar navegación">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto"></ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto ">
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('page.cargar')}}">Cargar<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Consumo</a>
                   <div  class="dropdown-menu" aria-labelledby="navbarDropdown">
                       <a class="dropdown-item" href="{{url_for('page.consumoDetallado')}}">Detallado</a>
                       <a class="dropdown-item" href="{{url_for('page.consumoMensual')}}">Mesual</a>
                       <a class="dropdown-item" href="#">Anual</a>
                   </div>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('page.inv')}}">Inventario</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " href="#">Rebaja</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " href="#">Merma</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " href="{{url_for('page.logout')}}">Cerrar Sesion</a>
                </li>
            </ul>
</nav>
{% endblock %}

{% block container %}
<style>
    body{color: #000;overflow-x: hidden;height: 100%;background-repeat: no-repeat;background-size: 100% 100%}.card{padding: 30px 40px;margin-top: 60px;margin-bottom: 60px;border: none !important;box-shadow: 0 6px 12px 0 rgba(0,0,0,0.2)}.blue-text{color: #00BCD4}.form-control-label{margin-bottom: 0}input, textarea, button{padding: 8px 15px;border-radius: 5px !important;margin: 5px 0px;box-sizing: border-box;border: 1px solid #ccc;font-size: 18px !important;font-weight: 300}input:focus, textarea:focus{-moz-box-shadow: none !important;-webkit-box-shadow: none !important;box-shadow: none !important;border: 1px solid #00BCD4;outline-width: 0;font-weight: 400}.btn-block{text-transform: uppercase;font-size: 15px !important;font-weight: 400;height: 43px;cursor: pointer}.btn-block:hover{color: #fff !important}button:focus{-moz-box-shadow: none !important;-webkit-box-shadow: none !important;box-shadow: none !important;outline-width: 0}
</style>

<div class="container-fluid px-1 py-5 mx-auto">
    <div class="row d-flex justify-content-center">
        <div class="col-xl-7 col-lg-8 col-md-9 col-11 text-center">

            <br>
            <div class="card">

                <h5 class="text-center mb-4">Nota de Entrega</h5>
                <form method="POST" class="form-card" action="{{url_for('page.cargar')}}" name="cargar">

                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"\>

                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Fecha<span class="text-danger"> *</span></label> <input type="date"  name="fecha" placeholder="Indique la fecha" class="required" required > </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Turno<span class="text-danger"> *</span></label> <input type="text"  name="turno" placeholder="Indique el turno"  maxlength="25" class="required" required > </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-12 flex-column d-flex"> <label class="form-control-label px-3">Apellido y Nombre<span class="text-danger"> *</span></label> <input type="text"  name="nombre" maxlength="25" placeholder="Indique su nombre" class="required" required> </div>

                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Filtro<span class="text-danger"> </span></label> <input type="number" name="filtro" min="0" placeholder="Numero de piezas" > </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Micro Colectores<span class="text-danger"> </span></label> <input type="number"  min="0" name="colectores" placeholder="Numero de piezas"> </div>

                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Ependorf 0.5<span class="text-danger"> </span></label> <input type="number" name="ependrorf05" min="0" placeholder="Numero de piezas"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Ependorf 0.2<span class="text-danger"> </span></label> <input type="number"  name="ependrorf02" min="0" placeholder="Numero de piezas"> </div>

                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Ependorf 2<span class="text-danger"> </span></label> <input type="number" name="ependrorf2" min="0" placeholder="Numero de piezas"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Puntas 10<span class="text-danger"> </span></label> <input type="number" name="puntas10" min="0" placeholder="Numero de piezas"> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Puntas 1000<span class="text-danger"> </span></label> <input type="number"  name="puntas1000" min="0" placeholder="Numero de piezas"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Kit Amplificacion 96 <span class="text-danger"> </span></label> <input type="number"  step="0.1" min="0" name="amplificacion" placeholder="Numero de piezas"> </div>

                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">WS1 mL<span class="text-danger"> </span></label> <input type="number" step="0.1" name="ws1" min="0" placeholder="Numero de mL"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">WS2 mL<span class="text-danger"> </span></label> <input type="number" step="0.1" name="ws2"  min="0"placeholder="Numero de mL"> </div>

                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">SSB mL<span class="text-danger"> </span></label> <input type="number" step="0.1" name="ssb"  min="0" placeholder="Numero de mL"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">EB mL<span class="text-danger"> </span></label> <input type="number" step="0.1" name="eb"  min="0" placeholder="Numero de mL"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Hisopo<span class="text-danger"> </span></label> <input type="number"  name="hisopos" min="0" placeholder="Numero de piezas"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Kit Amplificacion 24 <span class="text-danger"> *</span></label> <input type="number"  step="0.1" min="0" name="amplificacion24" placeholder="Numero de piezas"> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-12 flex-column d-flex"> <label class="form-control-label px-3">Observaciones<span class="text-danger"> </span></label> <input type="text" name="observacion" placeholder="Observaciones"> </div>
                    </div>
                    <div class="row justify-content-end">
                        <div class="form-group col-sm-6"> <button type="submit" class="btn-block btn-primary" name="cargar">Cargar</button> </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}